use crate::models::DataTypeInfo;

/// Returns the list of data types supported by MySQL/MariaDB.
/// Includes spatial types for geometric data.
pub fn get_data_types() -> Vec<DataTypeInfo> {
    vec![
        // Numeric types
        DataTypeInfo {
            name: "TINYINT".to_string(),
            category: "numeric".to_string(),
            requires_length: false,
            requires_precision: false,
            default_length: None,
            supports_auto_increment: true,
            requires_extension: None,
        },
        DataTypeInfo {
            name: "SMALLINT".to_string(),
            category: "numeric".to_string(),
            requires_length: false,
            requires_precision: false,
            default_length: None,
            supports_auto_increment: true,
            requires_extension: None,
        },
        DataTypeInfo {
            name: "MEDIUMINT".to_string(),
            category: "numeric".to_string(),
            requires_length: false,
            requires_precision: false,
            default_length: None,
            supports_auto_increment: true,
            requires_extension: None,
        },
        DataTypeInfo {
            name: "INTEGER".to_string(),
            category: "numeric".to_string(),
            requires_length: false,
            requires_precision: false,
            default_length: None,
            supports_auto_increment: true,
            requires_extension: None,
        },
        DataTypeInfo {
            name: "BIGINT".to_string(),
            category: "numeric".to_string(),
            requires_length: false,
            requires_precision: false,
            default_length: None,
            supports_auto_increment: true,
            requires_extension: None,
        },
        DataTypeInfo {
            name: "DECIMAL".to_string(),
            category: "numeric".to_string(),
            requires_length: false,
            requires_precision: true,
            default_length: Some("10,2".to_string()),
            supports_auto_increment: false,
            requires_extension: None,
        },
        DataTypeInfo {
            name: "FLOAT".to_string(),
            category: "numeric".to_string(),
            requires_length: false,
            requires_precision: false,
            default_length: None,
            supports_auto_increment: false,
            requires_extension: None,
        },
        DataTypeInfo {
            name: "DOUBLE".to_string(),
            category: "numeric".to_string(),
            requires_length: false,
            requires_precision: false,
            default_length: None,
            supports_auto_increment: false,
            requires_extension: None,
        },
        // String types
        DataTypeInfo {
            name: "CHAR".to_string(),
            category: "string".to_string(),
            requires_length: true,
            requires_precision: false,
            default_length: Some("10".to_string()),
            supports_auto_increment: false,
            requires_extension: None,
        },
        DataTypeInfo {
            name: "VARCHAR".to_string(),
            category: "string".to_string(),
            requires_length: true,
            requires_precision: false,
            default_length: Some("255".to_string()),
            supports_auto_increment: false,
            requires_extension: None,
        },
        DataTypeInfo {
            name: "TINYTEXT".to_string(),
            category: "string".to_string(),
            requires_length: false,
            requires_precision: false,
            default_length: None,
            supports_auto_increment: false,
            requires_extension: None,
        },
        DataTypeInfo {
            name: "TEXT".to_string(),
            category: "string".to_string(),
            requires_length: false,
            requires_precision: false,
            default_length: None,
            supports_auto_increment: false,
            requires_extension: None,
        },
        DataTypeInfo {
            name: "MEDIUMTEXT".to_string(),
            category: "string".to_string(),
            requires_length: false,
            requires_precision: false,
            default_length: None,
            supports_auto_increment: false,
            requires_extension: None,
        },
        DataTypeInfo {
            name: "LONGTEXT".to_string(),
            category: "string".to_string(),
            requires_length: false,
            requires_precision: false,
            default_length: None,
            supports_auto_increment: false,
            requires_extension: None,
        },
        // Boolean (alias for TINYINT(1))
        DataTypeInfo {
            name: "BOOLEAN".to_string(),
            category: "other".to_string(),
            requires_length: false,
            requires_precision: false,
            default_length: None,
            supports_auto_increment: false,
            requires_extension: None,
        },
        // Date/Time types
        DataTypeInfo {
            name: "DATE".to_string(),
            category: "date".to_string(),
            requires_length: false,
            requires_precision: false,
            default_length: None,
            supports_auto_increment: false,
            requires_extension: None,
        },
        DataTypeInfo {
            name: "TIME".to_string(),
            category: "date".to_string(),
            requires_length: false,
            requires_precision: false,
            default_length: None,
            supports_auto_increment: false,
            requires_extension: None,
        },
        DataTypeInfo {
            name: "DATETIME".to_string(),
            category: "date".to_string(),
            requires_length: false,
            requires_precision: false,
            default_length: None,
            supports_auto_increment: false,
            requires_extension: None,
        },
        DataTypeInfo {
            name: "TIMESTAMP".to_string(),
            category: "date".to_string(),
            requires_length: false,
            requires_precision: false,
            default_length: None,
            supports_auto_increment: false,
            requires_extension: None,
        },
        DataTypeInfo {
            name: "YEAR".to_string(),
            category: "date".to_string(),
            requires_length: false,
            requires_precision: false,
            default_length: None,
            supports_auto_increment: false,
            requires_extension: None,
        },
        // JSON
        DataTypeInfo {
            name: "JSON".to_string(),
            category: "json".to_string(),
            requires_length: false,
            requires_precision: false,
            default_length: None,
            supports_auto_increment: false,
            requires_extension: None,
        },
        // Binary types
        DataTypeInfo {
            name: "BINARY".to_string(),
            category: "binary".to_string(),
            requires_length: true,
            requires_precision: false,
            default_length: Some("255".to_string()),
            supports_auto_increment: false,
            requires_extension: None,
        },
        DataTypeInfo {
            name: "VARBINARY".to_string(),
            category: "binary".to_string(),
            requires_length: true,
            requires_precision: false,
            default_length: Some("255".to_string()),
            supports_auto_increment: false,
            requires_extension: None,
        },
        DataTypeInfo {
            name: "TINYBLOB".to_string(),
            category: "binary".to_string(),
            requires_length: false,
            requires_precision: false,
            default_length: None,
            supports_auto_increment: false,
            requires_extension: None,
        },
        DataTypeInfo {
            name: "BLOB".to_string(),
            category: "binary".to_string(),
            requires_length: false,
            requires_precision: false,
            default_length: None,
            supports_auto_increment: false,
            requires_extension: None,
        },
        DataTypeInfo {
            name: "MEDIUMBLOB".to_string(),
            category: "binary".to_string(),
            requires_length: false,
            requires_precision: false,
            default_length: None,
            supports_auto_increment: false,
            requires_extension: None,
        },
        DataTypeInfo {
            name: "LONGBLOB".to_string(),
            category: "binary".to_string(),
            requires_length: false,
            requires_precision: false,
            default_length: None,
            supports_auto_increment: false,
            requires_extension: None,
        },
        // Spatial types
        DataTypeInfo {
            name: "GEOMETRY".to_string(),
            category: "spatial".to_string(),
            requires_length: false,
            requires_precision: false,
            default_length: None,
            supports_auto_increment: false,
            requires_extension: None,
        },
        DataTypeInfo {
            name: "POINT".to_string(),
            category: "spatial".to_string(),
            requires_length: false,
            requires_precision: false,
            default_length: None,
            supports_auto_increment: false,
            requires_extension: None,
        },
        DataTypeInfo {
            name: "LINESTRING".to_string(),
            category: "spatial".to_string(),
            requires_length: false,
            requires_precision: false,
            default_length: None,
            supports_auto_increment: false,
            requires_extension: None,
        },
        DataTypeInfo {
            name: "POLYGON".to_string(),
            category: "spatial".to_string(),
            requires_length: false,
            requires_precision: false,
            default_length: None,
            supports_auto_increment: false,
            requires_extension: None,
        },
        DataTypeInfo {
            name: "MULTIPOINT".to_string(),
            category: "spatial".to_string(),
            requires_length: false,
            requires_precision: false,
            default_length: None,
            supports_auto_increment: false,
            requires_extension: None,
        },
        DataTypeInfo {
            name: "MULTILINESTRING".to_string(),
            category: "spatial".to_string(),
            requires_length: false,
            requires_precision: false,
            default_length: None,
            supports_auto_increment: false,
            requires_extension: None,
        },
        DataTypeInfo {
            name: "MULTIPOLYGON".to_string(),
            category: "spatial".to_string(),
            requires_length: false,
            requires_precision: false,
            default_length: None,
            supports_auto_increment: false,
            requires_extension: None,
        },
        DataTypeInfo {
            name: "GEOMETRYCOLLECTION".to_string(),
            category: "spatial".to_string(),
            requires_length: false,
            requires_precision: false,
            default_length: None,
            supports_auto_increment: false,
            requires_extension: None,
        },
    ]
}
