-- =============================================================
-- Tabularis Demo — Perf / wide-table stress test (MySQL 8)
-- Database: perf_demo
-- Table:    wide_table  ->  50 columns x 50,000 rows
-- Purpose:  reproduce slow-scroll reports with many columns/rows so
--           DataGrid virtualization/memoization can be profiled.
-- NOTE: heavy dataset — first container boot takes a little longer.
-- Generated by demo/generate-perf-sql.py (edit there, then re-run).
-- =============================================================

SET NAMES utf8mb4;

CREATE DATABASE IF NOT EXISTS perf_demo
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE perf_demo;

DROP TABLE IF EXISTS wide_table;

CREATE TABLE wide_table (
    id BIGINT NOT NULL PRIMARY KEY,
    json_data JSON,
    long_text TEXT,
    created_at DATETIME,
    updated_at DATETIME,
    birth_date DATE,
    is_active TINYINT(1),
    is_verified TINYINT(1),
    amount DECIMAL(12,2),
    balance DECIMAL(14,4),
    score DOUBLE,
    big_value BIGINT,
    attr_01 VARCHAR(80),
    attr_02 INT,
    attr_03 DECIMAL(12,2),
    attr_04 VARCHAR(80),
    attr_05 INT,
    attr_06 DECIMAL(12,2),
    attr_07 VARCHAR(80),
    attr_08 INT,
    attr_09 DECIMAL(12,2),
    attr_10 VARCHAR(80),
    attr_11 INT,
    attr_12 DECIMAL(12,2),
    attr_13 VARCHAR(80),
    attr_14 INT,
    attr_15 DECIMAL(12,2),
    attr_16 VARCHAR(80),
    attr_17 INT,
    attr_18 DECIMAL(12,2),
    attr_19 VARCHAR(80),
    attr_20 INT,
    attr_21 DECIMAL(12,2),
    attr_22 VARCHAR(80),
    attr_23 INT,
    attr_24 DECIMAL(12,2),
    attr_25 VARCHAR(80),
    attr_26 INT,
    attr_27 DECIMAL(12,2),
    attr_28 VARCHAR(80),
    attr_29 INT,
    attr_30 DECIMAL(12,2),
    attr_31 VARCHAR(80),
    attr_32 INT,
    attr_33 DECIMAL(12,2),
    attr_34 VARCHAR(80),
    attr_35 INT,
    attr_36 DECIMAL(12,2),
    attr_37 VARCHAR(80),
    attr_38 INT
) ENGINE=InnoDB;

-- 50k rows via 5 cross-joined digit tables (0..9 each -> 0..99999), filtered.
INSERT INTO wide_table (
    id, json_data, long_text, created_at, updated_at, birth_date, is_active, is_verified, amount, balance, score, big_value, attr_01, attr_02, attr_03, attr_04, attr_05, attr_06, attr_07, attr_08, attr_09, attr_10, attr_11, attr_12, attr_13, attr_14, attr_15, attr_16, attr_17, attr_18, attr_19, attr_20, attr_21, attr_22, attr_23, attr_24, attr_25, attr_26, attr_27, attr_28, attr_29, attr_30, attr_31, attr_32, attr_33, attr_34, attr_35, attr_36, attr_37, attr_38
)
SELECT
    g.g,
    JSON_OBJECT('row', g.g, 'label', CONCAT('item-', g.g), 'tags', JSON_ARRAY('alpha','beta', g.g MOD 7)),
    REPEAT(CONCAT('Lorem ipsum dolor row ', g.g, '. '), 6),
    DATE_ADD('2000-01-01 00:00:00', INTERVAL g.g SECOND),
    DATE_ADD('2010-01-01 00:00:00', INTERVAL (g.g*2) SECOND),
    DATE_ADD('1970-01-01', INTERVAL (g.g MOD 18000) DAY),
    (g.g MOD 2 = 0),
    (g.g MOD 3 = 0),
    ROUND((g.g MOD 100000) * 1.25, 2),
    ROUND((g.g MOD 50000) * 0.337, 4),
    (g.g * 0.5),
    (g.g * 1000003),
    CONCAT('attr1-', g.g),
    ((g.g * 2) MOD 100000),
    ROUND((g.g MOD 9999) * 3 * 0.1, 2),
    CONCAT('attr4-', g.g),
    ((g.g * 5) MOD 100000),
    ROUND((g.g MOD 9999) * 6 * 0.1, 2),
    CONCAT('attr7-', g.g),
    ((g.g * 8) MOD 100000),
    ROUND((g.g MOD 9999) * 9 * 0.1, 2),
    CONCAT('attr10-', g.g),
    ((g.g * 11) MOD 100000),
    ROUND((g.g MOD 9999) * 12 * 0.1, 2),
    CONCAT('attr13-', g.g),
    ((g.g * 14) MOD 100000),
    ROUND((g.g MOD 9999) * 15 * 0.1, 2),
    CONCAT('attr16-', g.g),
    ((g.g * 17) MOD 100000),
    ROUND((g.g MOD 9999) * 18 * 0.1, 2),
    CONCAT('attr19-', g.g),
    ((g.g * 20) MOD 100000),
    ROUND((g.g MOD 9999) * 21 * 0.1, 2),
    CONCAT('attr22-', g.g),
    ((g.g * 23) MOD 100000),
    ROUND((g.g MOD 9999) * 24 * 0.1, 2),
    CONCAT('attr25-', g.g),
    ((g.g * 26) MOD 100000),
    ROUND((g.g MOD 9999) * 27 * 0.1, 2),
    CONCAT('attr28-', g.g),
    ((g.g * 29) MOD 100000),
    ROUND((g.g MOD 9999) * 30 * 0.1, 2),
    CONCAT('attr31-', g.g),
    ((g.g * 32) MOD 100000),
    ROUND((g.g MOD 9999) * 33 * 0.1, 2),
    CONCAT('attr34-', g.g),
    ((g.g * 35) MOD 100000),
    ROUND((g.g MOD 9999) * 36 * 0.1, 2),
    CONCAT('attr37-', g.g),
    ((g.g * 38) MOD 100000)
FROM (
    SELECT (d5.d*10000 + d4.d*1000 + d3.d*100 + d2.d*10 + d1.d) + 1 AS g
    FROM (SELECT 0 d UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d1
    CROSS JOIN (SELECT 0 d UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d2
    CROSS JOIN (SELECT 0 d UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d3
    CROSS JOIN (SELECT 0 d UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d4
    CROSS JOIN (SELECT 0 d UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d5
) AS g
WHERE g.g <= 50000;
