#!/usr/bin/env python3
"""Generate the perf "wide table" seed for the demo stack (MySQL + Postgres).

Produces a `perf_demo.wide_table` with 50 columns (id + 49 data columns of
mixed types) and 50_000 rows, used to stress-test DataGrid scroll performance.

Run from the repo root:  python3 demo/generate-perf-sql.py
Writes: demo/init/mysql/06-perf-wide.sql, demo/init/postgres/06-perf-wide.sql
"""

ROWS = 50000

# Each spec: (name, mysql_type, pg_type, mysql_expr, pg_expr)
# {g} is the row counter (1..ROWS) and is the same variable name in both dialects.
specials = [
    ("json_data", "JSON", "JSONB",
     "JSON_OBJECT('row', {g}, 'label', CONCAT('item-', {g}), 'tags', JSON_ARRAY('alpha','beta', {g} MOD 7))",
     "jsonb_build_object('row', {g}, 'label', 'item-' || {g}, 'tags', jsonb_build_array('alpha','beta', {g} % 7))"),
    ("long_text", "TEXT", "TEXT",
     "REPEAT(CONCAT('Lorem ipsum dolor row ', {g}, '. '), 6)",
     "repeat('Lorem ipsum dolor row ' || {g} || '. ', 6)"),
    ("created_at", "DATETIME", "TIMESTAMP",
     "DATE_ADD('2000-01-01 00:00:00', INTERVAL {g} SECOND)",
     "TIMESTAMP '2000-01-01 00:00:00' + ({g} * INTERVAL '1 second')"),
    ("updated_at", "DATETIME", "TIMESTAMP",
     "DATE_ADD('2010-01-01 00:00:00', INTERVAL ({g}*2) SECOND)",
     "TIMESTAMP '2010-01-01 00:00:00' + (({g}*2) * INTERVAL '1 second')"),
    ("birth_date", "DATE", "DATE",
     "DATE_ADD('1970-01-01', INTERVAL ({g} MOD 18000) DAY)",
     "DATE '1970-01-01' + ({g} % 18000)"),
    ("is_active", "TINYINT(1)", "BOOLEAN",
     "({g} MOD 2)",
     "({g} % 2 = 0)"),
    ("is_verified", "TINYINT(1)", "BOOLEAN",
     "({g} MOD 3 = 0)",
     "({g} % 3 = 0)"),
    ("amount", "DECIMAL(12,2)", "DECIMAL(12,2)",
     "ROUND(({g} MOD 100000) * 1.25, 2)",
     "ROUND((({g} % 100000) * 1.25)::numeric, 2)"),
    ("balance", "DECIMAL(14,4)", "DECIMAL(14,4)",
     "ROUND(({g} MOD 50000) * 0.337, 4)",
     "ROUND((({g} % 50000) * 0.337)::numeric, 4)"),
    ("score", "DOUBLE", "DOUBLE PRECISION",
     "({g} * 0.5)",
     "({g} * 0.5)"),
    ("big_value", "BIGINT", "BIGINT",
     "({g} * 1000003)",
     "({g}::bigint * 1000003)"),
]

# Fill the remaining columns up to 49 data columns with attr_NN cycling types.
DATA_COLS = 49
fill_count = DATA_COLS - len(specials)
cycle = ["varchar", "int", "decimal"]

fills = []
for i in range(fill_count):
    idx = i + 1
    name = f"attr_{idx:02d}"
    kind = cycle[i % len(cycle)]
    if kind == "varchar":
        fills.append((name, "VARCHAR(80)", "VARCHAR(80)",
                      f"CONCAT('attr{idx}-', {{g}})",
                      f"'attr{idx}-' || {{g}}"))
    elif kind == "int":
        fills.append((name, "INT", "INTEGER",
                      f"(({{g}} * {idx}) MOD 100000)",
                      f"(({{g}} * {idx}) % 100000)"))
    else:  # decimal
        fills.append((name, "DECIMAL(12,2)", "DECIMAL(12,2)",
                      f"ROUND(({{g}} MOD 9999) * {idx} * 0.1, 2)",
                      f"ROUND((({{g}} % 9999) * {idx} * 0.1)::numeric, 2)"))

cols = specials + fills
assert len(cols) == DATA_COLS, len(cols)

HEADER = f"""-- =============================================================
-- Tabularis Demo — Perf / wide-table stress test ({{engine}})
-- Database: perf_demo
-- Table:    wide_table  ->  50 columns x {ROWS:,} rows
-- Purpose:  reproduce slow-scroll reports with many columns/rows so
--           DataGrid virtualization/memoization can be profiled.
-- NOTE: heavy dataset — first container boot takes a little longer.
-- Generated by demo/generate-perf-sql.py (edit there, then re-run).
-- ============================================================="""

# ---- MySQL ----------------------------------------------------------------
my_coldefs = ["    id BIGINT NOT NULL PRIMARY KEY"]
for name, mty, _pty, _me, _pe in cols:
    my_coldefs.append(f"    {name} {mty}")
my_collist = ",\n".join(my_coldefs)

my_insert_cols = ["id"] + [c[0] for c in cols]
my_insert_exprs = ["g.g"] + [c[3].replace("{g}", "g.g") for c in cols]

digit = "(SELECT 0 d UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9)"

mysql = f"""{HEADER.replace("{engine}", "MySQL 8")}

SET NAMES utf8mb4;

CREATE DATABASE IF NOT EXISTS perf_demo
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE perf_demo;

DROP TABLE IF EXISTS wide_table;

CREATE TABLE wide_table (
{my_collist}
) ENGINE=InnoDB;

-- 50k rows via 5 cross-joined digit tables (0..9 each -> 0..99999), filtered.
INSERT INTO wide_table (
    {", ".join(my_insert_cols)}
)
SELECT
    {",\n    ".join(my_insert_exprs)}
FROM (
    SELECT (d5.d*10000 + d4.d*1000 + d3.d*100 + d2.d*10 + d1.d) + 1 AS g
    FROM {digit} d1
    CROSS JOIN {digit} d2
    CROSS JOIN {digit} d3
    CROSS JOIN {digit} d4
    CROSS JOIN {digit} d5
) AS g
WHERE g.g <= {ROWS};
"""

# ---- Postgres -------------------------------------------------------------
pg_coldefs = ["    id BIGINT NOT NULL PRIMARY KEY"]
for name, _mty, pty, _me, _pe in cols:
    pg_coldefs.append(f"    {name} {pty}")
pg_collist = ",\n".join(pg_coldefs)

pg_insert_cols = ["id"] + [c[0] for c in cols]
pg_insert_exprs = ["g"] + [c[4].replace("{g}", "g") for c in cols]

postgres = f"""{HEADER.replace("{engine}", "PostgreSQL 16")}

CREATE DATABASE perf_demo;

\\connect perf_demo

DROP TABLE IF EXISTS wide_table;

CREATE TABLE wide_table (
{pg_collist}
);

INSERT INTO wide_table (
    {", ".join(pg_insert_cols)}
)
SELECT
    {",\n    ".join(pg_insert_exprs)}
FROM generate_series(1, {ROWS}) AS g;
"""

with open("demo/init/mysql/06-perf-wide.sql", "w") as f:
    f.write(mysql)
with open("demo/init/postgres/06-perf-wide.sql", "w") as f:
    f.write(postgres)

print("wrote", DATA_COLS + 1, "columns,", ROWS, "rows")
