-- =============================================================
-- Tabularis Demo — Perf / wide-table stress test (PostgreSQL 16)
-- Database: perf_demo
-- Table:    wide_table  ->  50 columns x 50,000 rows
-- Purpose:  reproduce slow-scroll reports with many columns/rows so
--           DataGrid virtualization/memoization can be profiled.
-- NOTE: heavy dataset — first container boot takes a little longer.
-- Generated by demo/generate-perf-sql.py (edit there, then re-run).
-- =============================================================

CREATE DATABASE perf_demo;

\connect perf_demo

DROP TABLE IF EXISTS wide_table;

CREATE TABLE wide_table (
    id BIGINT NOT NULL PRIMARY KEY,
    json_data JSONB,
    long_text TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    birth_date DATE,
    is_active BOOLEAN,
    is_verified BOOLEAN,
    amount DECIMAL(12,2),
    balance DECIMAL(14,4),
    score DOUBLE PRECISION,
    big_value BIGINT,
    attr_01 VARCHAR(80),
    attr_02 INTEGER,
    attr_03 DECIMAL(12,2),
    attr_04 VARCHAR(80),
    attr_05 INTEGER,
    attr_06 DECIMAL(12,2),
    attr_07 VARCHAR(80),
    attr_08 INTEGER,
    attr_09 DECIMAL(12,2),
    attr_10 VARCHAR(80),
    attr_11 INTEGER,
    attr_12 DECIMAL(12,2),
    attr_13 VARCHAR(80),
    attr_14 INTEGER,
    attr_15 DECIMAL(12,2),
    attr_16 VARCHAR(80),
    attr_17 INTEGER,
    attr_18 DECIMAL(12,2),
    attr_19 VARCHAR(80),
    attr_20 INTEGER,
    attr_21 DECIMAL(12,2),
    attr_22 VARCHAR(80),
    attr_23 INTEGER,
    attr_24 DECIMAL(12,2),
    attr_25 VARCHAR(80),
    attr_26 INTEGER,
    attr_27 DECIMAL(12,2),
    attr_28 VARCHAR(80),
    attr_29 INTEGER,
    attr_30 DECIMAL(12,2),
    attr_31 VARCHAR(80),
    attr_32 INTEGER,
    attr_33 DECIMAL(12,2),
    attr_34 VARCHAR(80),
    attr_35 INTEGER,
    attr_36 DECIMAL(12,2),
    attr_37 VARCHAR(80),
    attr_38 INTEGER
);

INSERT INTO wide_table (
    id, json_data, long_text, created_at, updated_at, birth_date, is_active, is_verified, amount, balance, score, big_value, attr_01, attr_02, attr_03, attr_04, attr_05, attr_06, attr_07, attr_08, attr_09, attr_10, attr_11, attr_12, attr_13, attr_14, attr_15, attr_16, attr_17, attr_18, attr_19, attr_20, attr_21, attr_22, attr_23, attr_24, attr_25, attr_26, attr_27, attr_28, attr_29, attr_30, attr_31, attr_32, attr_33, attr_34, attr_35, attr_36, attr_37, attr_38
)
SELECT
    g,
    jsonb_build_object('row', g, 'label', 'item-' || g, 'tags', jsonb_build_array('alpha','beta', g % 7)),
    repeat('Lorem ipsum dolor row ' || g || '. ', 6),
    TIMESTAMP '2000-01-01 00:00:00' + (g * INTERVAL '1 second'),
    TIMESTAMP '2010-01-01 00:00:00' + ((g*2) * INTERVAL '1 second'),
    DATE '1970-01-01' + (g % 18000),
    (g % 2 = 0),
    (g % 3 = 0),
    ROUND(((g % 100000) * 1.25)::numeric, 2),
    ROUND(((g % 50000) * 0.337)::numeric, 4),
    (g * 0.5),
    (g::bigint * 1000003),
    'attr1-' || g,
    ((g * 2) % 100000),
    ROUND(((g % 9999) * 3 * 0.1)::numeric, 2),
    'attr4-' || g,
    ((g * 5) % 100000),
    ROUND(((g % 9999) * 6 * 0.1)::numeric, 2),
    'attr7-' || g,
    ((g * 8) % 100000),
    ROUND(((g % 9999) * 9 * 0.1)::numeric, 2),
    'attr10-' || g,
    ((g * 11) % 100000),
    ROUND(((g % 9999) * 12 * 0.1)::numeric, 2),
    'attr13-' || g,
    ((g * 14) % 100000),
    ROUND(((g % 9999) * 15 * 0.1)::numeric, 2),
    'attr16-' || g,
    ((g * 17) % 100000),
    ROUND(((g % 9999) * 18 * 0.1)::numeric, 2),
    'attr19-' || g,
    ((g * 20) % 100000),
    ROUND(((g % 9999) * 21 * 0.1)::numeric, 2),
    'attr22-' || g,
    ((g * 23) % 100000),
    ROUND(((g % 9999) * 24 * 0.1)::numeric, 2),
    'attr25-' || g,
    ((g * 26) % 100000),
    ROUND(((g % 9999) * 27 * 0.1)::numeric, 2),
    'attr28-' || g,
    ((g * 29) % 100000),
    ROUND(((g % 9999) * 30 * 0.1)::numeric, 2),
    'attr31-' || g,
    ((g * 32) % 100000),
    ROUND(((g % 9999) * 33 * 0.1)::numeric, 2),
    'attr34-' || g,
    ((g * 35) % 100000),
    ROUND(((g % 9999) * 36 * 0.1)::numeric, 2),
    'attr37-' || g,
    ((g * 38) % 100000)
FROM generate_series(1, 50000) AS g;
